const gameMap={
    name: "first map",
    id: 'first_map',
    values:[
        'gG','gG','gG','gG','gG','gG','hG','hG','hG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','wS','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','wS','wS','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG', 'gG','gG',,'gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG','gG',
        'gG','gG','gG','gG','gG','gG','gG','gG','gG',
    ]
}
